name: Builds Gradle sample

on:
  push:
    branches:
    - master
    paths:
    - gradle/**
  pull_request:
    paths:
    - gradle/**

env:
  LAUNCHABLE_TOKEN: ${{ secrets.GRADLE_EXAMPLE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Pull request validation
      if: github.event_name == 'pull_request'
      run: |
        cd gradle
        ./ci.sh

    - name: Full build
      if: github.event_name == 'push'
      run: |
        cd gradle
        ./ci.sh
