name: Builds Gradle sample

on:
  push:
    paths:
    - 'gradle/**'
  pull_request:
    paths:
    - 'gradle/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Start build
      run: |
        cd gradle
        ./ci.sh
